spring.datasource.url=jdbc:postgresql://localhost/ventiflow
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name = org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false
spring.jpa.format-sql=false
