spring.datasource.url=jdbc:postgresql://${DB_HOST}:5432/${DB_VENTIFLOW}?characterEncoding=UTF-8
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name = org.postgresql.Driver

# psql -h localhost -p 5432 -U postgres -d ventiflow

spring.jpa.hibernate.ddl-auto=update

# Mantiene el reinicio automático pero apaga el reporte de errores de DevTools
server.error.include-stacktrace=never
server.error.include-message=never

spring.jpa.show-sql=false
spring.jpa.format-sql=false